apiVersion: v1
kind: Pod
metadata:
  name: pod-{{ .Release.Name }}
spec:
  containers:
  - name: {{ .Release.Name }}-con
    image: oneilsh/ktesting-nfsclient
    env:
    - name: NFS_SVC
      value: {{ .Values.datastorage }}
    - name: TARGET_DIR
      value: {{ .Values.targetdir }}
    securityContext:
      capabilities:
        add: ["SYS_ADMIN", "SETPCAP"]
