stages:
- name: server
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:oneilsh-datastorage
      version: "0.8"
      name: studentvol
      targetNamespace: deploy
- name: clients
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:oneilsh-nfsclient
      version: "0.8"
      answers:
        datastorage: studentvol
        targetdir: /mnt/shared
      name: client1
      targetNamespace: deploy
  - applyAppConfig:
      catalogTemplate: cattle-global-data:oneilsh-nfsclient
      version: "0.8"
      answers:
        datastorage: studentvol
        targetdir: /mnt/shared
      name: client2
      targetNamespace: deploy
timeout: 3
branch:
  include:
  - master
notification: {}
