stages:
- name: upgrade
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:oneilsh-datastorage
      version: "0.8"
      name: studentvol
      targetNamespace: deploy
  - applyAppConfig:
      catalogTemplate: cattle-global-data:oneilsh-nfsclient
      version: "0.8"
      answers:
        datastorage: studentvol
        targetdir: /mnt/studentvol
      name: studentserver
      targetNamespace: deploy
timeout: 3
branch:
  include:
  - master
notification: {}
