stages:
- name: server
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:oneilsh-datastorage
      version: "0.8"
      name: studentvol
      targetNamespace: deploy
- name: jlab
  steps:
  - applyAppConfig:
      catalogTemplate: p-x4c2f:oneilsh-ktesting-ds-jupyterlab
      version: 0.1.1
      name: ds-jupyterlab
      targetNamespace: jhubtests
timeout: 3
branch:
  include:
  - master
notification: {}
