apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    app: nfs-{{ .Values.name }}-pod
  ports:
  - port: 111
    protocol: UDP
    name: udp111
  - port: 2049
    protocol: TCP
    name: tcp2049

