apiVersion: v1
kind: ServiceAccount
metadata:
 name: configmapper-serviceaccount

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
 name: configmapper
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmapper-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: configmapper
subjects:
- kind: ServiceAccount
  name: configmapper-serviceaccount
  
